// Who drafts in this league, and how they behave.
//
// Team names change every year; the people do not. Ten seasons of history
// (2016-2025) join on the manager -- the same ten people the entire time --
// which is why the app identifies a slot by coach rather than by team name.
//
// Every pick in that history was made live and in person. There is no
// autodraft in this league, so a repeated pattern is a real habit and a noisy
// one is a genuinely unpredictable drafter, not a data artifact.
//
// Each entry is [recentMean, recentSpread, verdict, priorMean]:
//   recentMean    mean round of their first pick at that position, 2022-2025
//   recentSpread  range across those seasons; 0 means identical every year
//   verdict       how 2016-21 relates to it:
//                   confirmed   - the same behaviour for a decade
//                   steady-mean - same average, but they used to be erratic
//                   drifted     - they changed; the recent number is the real one
//                   noisy       - no usable pattern even recently
//   priorMean     the 2016-21 mean, kept so drift is visible rather than hidden
//
// Only the recent era establishes a habit. Averaging ten years would blend two
// different drafters -- Josh took his first QB in round 6 for six seasons and
// round 4.5 for the last four, and the decade average describes neither.
//
// Generated by tools/analyze_draft_tendencies.py; regenerate after a season.

/** Verdicts worth acting on. Anything else is treated as no signal. */
export const USABLE_VERDICTS = new Set(['confirmed', 'steady-mean', 'drifted']);

export const COACHES = [
  {
    name: 'Danny', yahoo: 'Danny Richards', team2025: 'Feel It In My Plums',
    first: {
      QB: [4.8, 7, 'noisy', 6.2],
      RB: [2.2, 2, 'confirmed', 1.5],
      WR: [1.2, 1, 'confirmed', 1.7],
      TE: [8.8, 3, 'noisy', 7.8],
      K: [13, 3, 'noisy', 13.3],
      DST: [12, 3, 'noisy', 10.5],
    },
    earlyMix: { RB: 38, WR: 50 },
  },
  {
    name: 'Rob K.', yahoo: 'Rob Ketter', team2025: 'Dad Bod',
    first: {
      QB: [4.8, 3, 'noisy', 4.7],
      RB: [1.2, 1, 'confirmed', 1.5],
      WR: [4, 5, 'noisy', 2.3],
      TE: [3.8, 2, 'drifted', 5.7],
      K: [12, 5, 'noisy', 13.5],
      DST: [12, 3, 'noisy', 12.7],
    },
    earlyMix: { RB: 42, WR: 25 },
  },
  {
    name: 'Drew', yahoo: 'Drew', team2025: "Youain't1styourlast",
    first: {
      QB: [6, 3, 'noisy', 6.7],
      RB: [2.5, 3, 'noisy', 1.8],
      WR: [1.8, 2, 'confirmed', 1.7],
      TE: [7.2, 5, 'noisy', 6.7],
      K: [13, 0, 'confirmed', 13.3],
      DST: [11.5, 4, 'noisy', 11.5],
    },
    earlyMix: { RB: 33, WR: 50 },
  },
  {
    name: 'Joel', yahoo: 'That Dad Coach', team2025: 'Do It Lady!',
    first: {
      QB: [7.2, 4, 'noisy', 6.7],
      RB: [1.8, 1, 'confirmed', 1.2],
      WR: [1.2, 1, 'drifted', 2.2],
      TE: [8, 6, 'noisy', 7.2],
      K: [12.5, 2, 'drifted', 14],
      DST: [12.2, 3, 'noisy', 12.7],
    },
    earlyMix: { RB: 33, WR: 54 },
  },
  {
    name: 'Mark', yahoo: 'mark Hayford', team2025: 'No Email till Brooklyn',
    first: {
      QB: [4, 7, 'noisy', 3.5],
      RB: [3.2, 4, 'noisy', 1.3],
      WR: [2.2, 3, 'noisy', 4.8],
      TE: [7.2, 2, 'drifted', 5.5],
      K: [13.5, 3, 'noisy', 13.5],
      DST: [13, 2, 'confirmed', 13.8],
    },
    earlyMix: { RB: 38, WR: 46 },
  },
  {
    name: 'Robert E.', yahoo: 'Robert Ellison', team2025: 'Harambe McHarambeface',
    first: {
      QB: [4.2, 5, 'noisy', 7.8],
      RB: [3, 3, 'noisy', 1.7],
      WR: [1.8, 3, 'noisy', 2.7],
      TE: [6, 8, 'noisy', 5.8],
      K: [14.2, 3, 'noisy', 13.3],
      DST: [12.5, 1, 'steady-mean', 12.3],
    },
    earlyMix: { RB: 25, WR: 54 },
  },
  {
    name: 'Erik', yahoo: 'erik', team2025: 'Vegan Beer',
    isMe: true,
    first: {
      QB: [4, 6, 'noisy', 8.5],
      RB: [1.5, 2, 'confirmed', 1.5],
      WR: [1.8, 1, 'confirmed', 2],
      TE: [8, 4, 'noisy', 8.2],
      K: [14.8, 1, 'confirmed', 14.8],
      DST: [13, 3, 'noisy', 12.3],
    },
    earlyMix: { RB: 38, WR: 46 },
  },
  {
    name: 'Brandon', yahoo: 'Brandon', team2025: '40 is a long way',
    first: {
      QB: [5.2, 2, 'steady-mean', 5.2],
      RB: [1.2, 1, 'confirmed', 1.3],
      WR: [2.5, 2, 'confirmed', 2],
      TE: [4.8, 5, 'noisy', 5.7],
      K: [11.5, 4, 'noisy', 12.8],
      DST: [11.5, 1, 'steady-mean', 10.8],
    },
    earlyMix: { RB: 33, WR: 42 },
  },
  {
    name: 'Alex', yahoo: 'Alex', team2025: 'Biz Fuck it',
    first: {
      QB: [6.8, 4, 'noisy', 6.7],
      RB: [1, 0, 'confirmed', 1.7],
      WR: [2, 0, 'steady-mean', 2.5],
      TE: [8.8, 5, 'noisy', 6.3],
      K: [12.8, 4, 'noisy', 14],
      DST: [10.8, 2, 'drifted', 12],
    },
    earlyMix: { RB: 50, WR: 38 },
  },
  {
    name: 'Josh', yahoo: 'Juice', team2025: 'The Juice is Loose',
    first: {
      QB: [4.5, 2, 'drifted', 6],
      RB: [3.2, 5, 'noisy', 1.8],
      WR: [1.8, 3, 'noisy', 2.2],
      TE: [3, 3, 'noisy', 9.3],
      K: [15, 0, 'confirmed', 14.3],
      DST: [12.2, 1, 'steady-mean', 12],
    },
    earlyMix: { RB: 29, WR: 38 },
  },
];

/** Legacy saved settings stored team names. Migrate them to coach names. */
export const TEAM_TO_COACH = Object.fromEntries(
  COACHES.flatMap((c) => [[c.team2025, c.name], [c.yahoo, c.name]]),
);

export const coachByName = (name) => COACHES.find((c) => c.name === name) || null;

/**
 * The positions this coach reliably takes early enough to be worth planning
 * around. Anything with a spread wider than RELIABLE_SPREAD is dropped -- an
 * average of "round 4" built from rounds 1 and 7 predicts nothing.
 */
export function reliableHabits(coach) {
  if (!coach) return [];
  return Object.entries(coach.first)
    .filter(([, [, , verdict]]) => USABLE_VERDICTS.has(verdict))
    .map(([pos, [mean, spread, verdict, priorMean]]) => ({
      pos, round: mean, spread, verdict, priorMean,
    }))
    .sort((a, b) => a.round - b.round);
}

/**
 * One-line human summary, e.g. "RB r1.0 (10yr), TE r3.8 (moved up from 5.7)".
 * The parenthetical is the confidence: a decade-long trait reads differently
 * from one that changed recently, and both differ from a bare average.
 */
export function habitSummary(coach) {
  const habits = reliableHabits(coach).filter((h) => h.pos !== 'K' && h.pos !== 'DST');
  if (!habits.length) return 'no reliable pattern';
  return habits.map((h) => {
    const r = `${h.pos} r${h.round.toFixed(1)}`;
    if (h.verdict === 'drifted' && h.priorMean != null) {
      const dir = h.round < h.priorMean ? 'moved up from' : 'moved back from';
      return `${r} (${dir} ${h.priorMean.toFixed(1)})`;
    }
    if (h.verdict === 'confirmed') return `${r} (10yr${h.spread === 0 ? ', never varies' : ''})`;
    return r;
  }).join(', ');
}

/**
 * Which coaches pick between now and your next turn, in order.
 * Pure: takes the snake math as an argument so it stays testable headlessly.
 */
export function coachesUntilMyTurn(draftOrder, slotOnClock, currentPickNo, myNextPickNo) {
  const out = [];
  for (let p = currentPickNo; p < myNextPickNo; p += 1) {
    const slot = slotOnClock(p);
    const name = draftOrder[slot - 1];
    if (name) out.push({ pickNo: p, slot, name, coach: coachByName(name) });
  }
  return out;
}

/**
 * Positions at elevated risk of being gone before your next pick, based on who
 * is actually on the clock between now and then.
 *
 * This adjusts *timing*, never value: it can tell you a tier will not survive,
 * it must not tell you a worse player is better. Returns positions with the
 * count of upcoming coaches whose reliable habit lands on or before this round.
 */
export function positionsAtRisk(upcoming, round) {
  const tally = {};
  for (const { coach } of upcoming) {
    for (const h of reliableHabits(coach)) {
      // A habit predicts a pick only once the coach has reached that round.
      if (round >= h.round - 1) tally[h.pos] = (tally[h.pos] || 0) + 1;
    }
  }
  return Object.entries(tally)
    .map(([pos, count]) => ({ pos, count }))
    .sort((a, b) => b.count - a.count);
}
